=== alien3211/TranslateTools/XML_dict/xbdict.dtd
<!ELEMENT indicator (#PCDATA)>
<!ELEMENT phonetic (#PCDATA)>
<!ELEMENT hwinfo (pronunciation | xr | pos | label | variant)*>
<!ELEMENT idiom (#PCDATA)>
<!ELEMENT xr (xrentry)*>
<!ELEMENT headword (#PCDATA | spl | lang)*>
<!ELEMENT prepsource (#PCDATA)>
<!ELEMENT variant (#PCDATA | spl)*>
<!ELEMENT lang (#PCDATA)>
<!ELEMENT pos (#PCDATA)>
<!ELEMENT pronunciation (phonetic)*>
<!ELEMENT idarex (#PCDATA)>
<!ELEMENT spl (#PCDATA)>
<!ELEMENT syntactic (senseinfo | semantic)*>
<!ELEMENT senseinfo (xr | pos | variant | label | pronunciation | indicator)*>
<!ELEMENT preptarget (#PCDATA)>
<!ELEMENT xrentry (#PCDATA)>
<!ELEMENT semantic (subsense | senseinfo)*>
<!ELEMENT label (#PCDATA | lang)*>
<!ELEMENT gloss (#PCDATA)>
<!ELEMENT subsense (trans | preposition | idiom | idarex | example | gloss)*>
<!ELEMENT preposition (#PCDATA | prepsource | preptarget)*>
<!ELEMENT i (#PCDATA)>
<!ELEMENT trans (#PCDATA | i)*>
<!ELEMENT entry (headword | hwinfo | syntactic)*>
<!ELEMENT xbdict (xi:include | xbdict | entry)+>
<!ELEMENT xi:include EMPTY>
<!ATTLIST xi:include href CDATA #IMPLIED>
<!ATTLIST xbdict xmlns:xi CDATA #FIXED "http://www.w3.org/2001/XInclude" >
<!ELEMENT example (#PCDATA)>

=== alien3211/TranslateTools/XML_dict/x.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE xbdict SYSTEM "xbdict.dtd">
<xbdict>
<entry>
  <headword>
    <spl>xenophobia</spl>
  </headword>
  <hwinfo>
    <pos>N</pos>
    <pronunciation>
      <phonetic>ˌzenəˈfəʊbɪə</phonetic>
    </pronunciation>
    <label>form</label>
  </hwinfo>
  <syntactic>
    <semantic>
      <subsense>
        <trans>ksenofobia</trans>
      </subsense>
    </semantic>
  </syntactic>
</entry>
<entry>
  <headword>
    <spl>Xerox</spl>
  </headword>
  <hwinfo>
    <pronunciation>
      <phonetic>ˈzɪərɒks</phonetic>
    </pronunciation>
  </hwinfo>
  <syntactic>
    <senseinfo>
      <pos>N</pos>
    </senseinfo>
    <semantic>
      <subsense>
        <trans>kserograf</trans>
      </subsense>
    </semantic>
    <semantic>
      <subsense>
        <trans>odbitka kserograficzna</trans>
      </subsense>
    </semantic>
  </syntactic>
  <syntactic>
    <senseinfo>
      <pos>V</pos>
    </senseinfo>
    <semantic>
      <subsense>
        <trans>kserografować</trans>
        <trans>kserować</trans>
      </subsense>
    </semantic>
  </syntactic>
</entry>
<entry>
  <headword>
    <spl>Xmas</spl>
  </headword>
  <hwinfo>
    <pronunciation>
      <phonetic>ˈkrɪsməs, ˈeksməs</phonetic>
    </pronunciation>
    <xr>
      <xrentry>Christmas</xrentry>
    </xr>
  </hwinfo>
  <syntactic>
    <semantic>
      <senseinfo>
        <label>nieform</label>
      </senseinfo>
      <subsense>
        <trans>Boże Narodzenie</trans>
      </subsense>
    </semantic>
  </syntactic>
</entry>
<entry>
  <headword>
    <spl>X-ray</spl>
  </headword>
  <hwinfo>
    <pronunciation>
      <phonetic>ˈeksreɪ</phonetic>
    </pronunciation>
  </hwinfo>
  <syntactic>
    <senseinfo>
      <pos>N</pos>
    </senseinfo>
    <semantic>
      <subsense>
        <trans>promień rentgena</trans>
      </subsense>
    </semantic>
    <semantic>
      <subsense>
        <trans>prześwietlenie rentgenowskie</trans>
      </subsense>
    </semantic>
    <semantic>
      <subsense>
        <trans>zdjęcie rentgenowskie</trans>
      </subsense>
    </semantic>
  </syntactic>
  <syntactic>
    <senseinfo>
      <pos>V</pos>
    </senseinfo>
    <semantic>
      <subsense>
        <trans>prześwietlać się promieniami rentgena</trans>
        <trans>prześwietlać się</trans>
      </subsense>
    </semantic>
  </syntactic>
</entry>
<entry>
  <headword>
    <spl>xylophone</spl>
  </headword>
  <hwinfo>
    <pos>N</pos>
    <pronunciation>
      <phonetic>ˈzaɪləfəʊn</phonetic>
    </pronunciation>
  </hwinfo>
  <syntactic>
    <semantic>
      <subsense>
        <trans>ksylofon</trans>
      </subsense>
    </semantic>
  </syntactic>
</entry>
</xbdict>
